INFO 2024-03-27 16:22:08,604 autoreload 7252 976 Watching for file changes with StatReloader
INFO 2024-03-27 16:22:16,696 basehttp 7252 7568 "GET / HTTP/1.1" 200 173
WARNING 2024-03-27 16:22:30,254 log 7252 3880 Not Found: /docs
WARNING 2024-03-27 16:22:30,256 basehttp 7252 3880 "GET /docs HTTP/1.1" 404 2421
WARNING 2024-03-27 16:22:31,172 log 7252 3880 Not Found: /about/
WARNING 2024-03-27 16:22:31,185 basehttp 7252 3880 "GET /about/ HTTP/1.1" 404 2427
INFO 2024-03-27 16:22:46,087 autoreload 7252 976 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\urls.py changed, reloading.
INFO 2024-03-27 16:22:47,914 autoreload 3424 2852 Watching for file changes with StatReloader
INFO 2024-03-27 16:22:52,741 basehttp 3424 8456 "GET /about/ HTTP/1.1" 200 162
INFO 2024-03-27 16:23:21,799 autoreload 3424 2852 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-03-27 16:23:23,161 autoreload 7668 9700 Watching for file changes with StatReloader
INFO 2024-03-27 16:23:25,941 basehttp 7668 6288 "GET /about/ HTTP/1.1" 200 164
INFO 2024-03-27 16:23:58,004 autoreload 7668 9700 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-03-27 16:23:59,462 autoreload 9576 7396 Watching for file changes with StatReloader
INFO 2024-03-27 16:24:01,236 basehttp 9576 5876 "GET /about/ HTTP/1.1" 200 164
INFO 2024-03-27 16:25:31,609 autoreload 9576 7396 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-03-27 16:25:32,937 autoreload 9716 1908 Watching for file changes with StatReloader
INFO 2024-03-27 16:26:28,547 autoreload 9716 1908 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-03-27 16:26:29,633 autoreload 5220 9408 Watching for file changes with StatReloader
INFO 2024-03-27 16:26:34,945 basehttp 5220 1148 "GET /about/ HTTP/1.1" 200 2113
INFO 2024-03-27 16:26:47,705 basehttp 5220 10476 "GET / HTTP/1.1" 200 1043
INFO 2024-04-01 20:49:15,433 autoreload 4076 5820 Watching for file changes with StatReloader
INFO 2024-04-01 20:49:42,759 autoreload 4076 5820 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\models.py changed, reloading.
INFO 2024-04-01 20:49:44,127 autoreload 11244 10208 Watching for file changes with StatReloader
INFO 2024-04-01 20:49:54,151 basehttp 11244 5332 "GET / HTTP/1.1" 200 1043
ERROR 2024-04-01 20:50:09,162 log 11244 8436 Internal Server Error: /create_users_fake/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: homeworkapp_clients

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 44, in create_users_fake
    client.save()
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: homeworkapp_clients
ERROR 2024-04-01 20:50:09,236 basehttp 11244 8436 "GET /create_users_fake/ HTTP/1.1" 500 147028
INFO 2024-04-01 20:53:29,952 autoreload 10008 2796 Watching for file changes with StatReloader
INFO 2024-04-01 20:53:33,773 basehttp 10008 4904 "GET / HTTP/1.1" 200 1043
INFO 2024-04-01 20:55:13,113 autoreload 8484 1684 Watching for file changes with StatReloader
INFO 2024-04-01 20:55:15,332 basehttp 8484 3680 "GET / HTTP/1.1" 200 1043
WARNING 2024-04-01 20:55:35,534 log 8484 3500 Not Found: /create_user_fake
WARNING 2024-04-01 20:55:35,536 basehttp 8484 3500 "GET /create_user_fake HTTP/1.1" 404 2647
ERROR 2024-04-01 20:55:55,513 log 8484 12204 Internal Server Error: /create_users_fake/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\middleware\clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
       ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
ERROR 2024-04-01 20:55:55,652 basehttp 8484 12204 "GET /create_users_fake/ HTTP/1.1" 500 64477
INFO 2024-04-01 20:58:28,964 autoreload 8484 1684 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-01 20:58:30,317 autoreload 9004 5968 Watching for file changes with StatReloader
INFO 2024-04-01 20:58:35,331 basehttp 9004 9192 "GET /create_users_fake/ HTTP/1.1" 200 2
INFO 2024-04-01 21:30:01,303 autoreload 448 10300 Watching for file changes with StatReloader
INFO 2024-04-01 21:30:05,655 basehttp 448 7948 "GET / HTTP/1.1" 200 1043
ERROR 2024-04-01 21:30:17,708 log 448 2880 Internal Server Error: /create_products/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\utils.py", line 98, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 51, in create_products
    product.save()
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1835, in execute_sql
    self.connection.ops.fetch_returned_insert_columns(
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\base\operations.py", line 216, in fetch_returned_insert_columns
    return cursor.fetchone()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\utils.py", line 97, in inner
    with self:
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\utils.py", line 98, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: database is locked
ERROR 2024-04-01 21:30:17,729 basehttp 448 2880 "GET /create_products/ HTTP/1.1" 500 124030
INFO 2024-04-01 21:30:38,838 basehttp 448 11848 "GET /create_products/ HTTP/1.1" 200 2
INFO 2024-04-01 22:16:08,746 autoreload 448 10300 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-01 22:16:11,320 autoreload 9048 1176 Watching for file changes with StatReloader
INFO 2024-04-01 22:21:06,664 autoreload 9048 1176 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-01 22:21:08,271 autoreload 9856 9892 Watching for file changes with StatReloader
INFO 2024-04-01 22:22:26,876 autoreload 9856 9892 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-01 22:22:28,525 autoreload 2468 7488 Watching for file changes with StatReloader
INFO 2024-04-01 22:25:20,667 autoreload 2468 7488 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-01 22:25:22,372 autoreload 11844 11652 Watching for file changes with StatReloader
INFO 2024-04-01 22:32:24,518 autoreload 11844 11652 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\urls.py changed, reloading.
INFO 2024-04-01 22:32:25,586 autoreload 2408 5544 Watching for file changes with StatReloader
INFO 2024-04-01 22:32:29,403 basehttp 2408 9828 "GET / HTTP/1.1" 200 1043
ERROR 2024-04-01 22:32:35,633 log 2408 10572 Internal Server Error: /create_orders/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 61, in create_orders
    total_price=Products.objects.filter(pk=j).first() * Products.objects.filter(pk=j).price())
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'price'
ERROR 2024-04-01 22:32:35,644 basehttp 2408 10572 "GET /create_orders/ HTTP/1.1" 500 65060
INFO 2024-04-01 22:34:22,643 autoreload 2408 5544 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-01 22:34:24,121 autoreload 12040 11528 Watching for file changes with StatReloader
ERROR 2024-04-01 22:34:26,361 log 12040 3604 Internal Server Error: /create_orders/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 61, in create_orders
    total_price=Products.objects.filter(pk=j).first() * Products.objects.filter(pk=j).first().price())
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'price'
ERROR 2024-04-01 22:34:26,430 basehttp 12040 3604 "GET /create_orders/ HTTP/1.1" 500 65229
INFO 2024-04-02 12:55:02,984 autoreload 3276 9620 Watching for file changes with StatReloader
INFO 2024-04-02 12:55:09,827 basehttp 3276 8440 "GET / HTTP/1.1" 200 1043
WARNING 2024-04-02 12:55:11,036 log 3276 8440 Not Found: /favicon.ico
WARNING 2024-04-02 12:55:11,110 basehttp 3276 8440 "GET /favicon.ico HTTP/1.1" 404 2624
ERROR 2024-04-02 12:55:15,670 log 3276 11880 Internal Server Error: /create_orders/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 62, in create_orders
    pk=j).first().price())
                  ^^^^^
AttributeError: 'NoneType' object has no attribute 'price'
ERROR 2024-04-02 12:55:15,678 basehttp 3276 11880 "GET /create_orders/ HTTP/1.1" 500 64858
INFO 2024-04-02 12:56:29,713 autoreload 3276 9620 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 12:56:31,211 autoreload 6576 10628 Watching for file changes with StatReloader
ERROR 2024-04-02 12:56:35,466 log 6576 9324 Internal Server Error: /create_orders/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 62, in create_orders
    pk=j).first().price())
                  ^^^^^^^
TypeError: 'decimal.Decimal' object is not callable
ERROR 2024-04-02 12:56:35,588 basehttp 6576 9324 "GET /create_orders/ HTTP/1.1" 500 64924
INFO 2024-04-02 13:00:58,097 autoreload 6576 10628 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 13:00:59,517 autoreload 12228 7444 Watching for file changes with StatReloader
ERROR 2024-04-02 13:01:03,245 log 12228 3724 Internal Server Error: /create_orders/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 61, in create_orders
    total_price=Products.objects.filter(pk=j).first() * Products.objects.filter(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for *: 'Products' and 'decimal.Decimal'
ERROR 2024-04-02 13:01:03,296 basehttp 12228 3724 "GET /create_orders/ HTTP/1.1" 500 65281
INFO 2024-04-02 13:01:47,306 autoreload 12228 7444 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 13:01:48,524 autoreload 5400 12148 Watching for file changes with StatReloader
ERROR 2024-04-02 13:01:52,044 log 5400 8548 Internal Server Error: /create_orders/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 59, in create_orders
    order = Orders(customer=Clients.objects.filter(pk=i).first(),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 564, in __init__
    _setattr(self, prop, value)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 659, in __set__
    raise TypeError(
TypeError: Direct assignment to the forward side of a many-to-many set is prohibited. Use products.set() instead.
ERROR 2024-04-02 13:01:52,067 basehttp 5400 8548 "GET /create_orders/ HTTP/1.1" 500 76441
INFO 2024-04-02 13:18:29,899 autoreload 5400 12148 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 13:18:31,285 autoreload 8424 2544 Watching for file changes with StatReloader
ERROR 2024-04-02 13:18:38,446 log 8424 9048 Internal Server Error: /create_orders/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 60, in create_orders
    products=Products.objects.filter(pk=j).set(),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'set'
ERROR 2024-04-02 13:18:38,458 basehttp 8424 9048 "GET /create_orders/ HTTP/1.1" 500 65312
INFO 2024-04-02 13:18:55,750 autoreload 8424 2544 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 13:18:57,293 autoreload 11284 2516 Watching for file changes with StatReloader
ERROR 2024-04-02 13:19:02,101 log 11284 912 Internal Server Error: /create_orders/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 60, in create_orders
    products=Products.objects.filter(pk=j).add(),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'add'
ERROR 2024-04-02 13:19:02,109 basehttp 11284 912 "GET /create_orders/ HTTP/1.1" 500 65312
INFO 2024-04-02 13:19:33,521 autoreload 11284 2516 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 13:19:34,704 autoreload 3984 2784 Watching for file changes with StatReloader
ERROR 2024-04-02 13:19:38,016 log 3984 3428 Internal Server Error: /create_orders/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 59, in create_orders
    order = Orders(customer=Clients.objects.filter(pk=i).first(),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 564, in __init__
    _setattr(self, prop, value)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 659, in __set__
    raise TypeError(
TypeError: Direct assignment to the forward side of a many-to-many set is prohibited. Use products.set() instead.
ERROR 2024-04-02 13:19:38,033 basehttp 3984 3428 "GET /create_orders/ HTTP/1.1" 500 76490
INFO 2024-04-02 13:20:33,621 autoreload 3984 2784 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 13:20:34,978 autoreload 5972 7904 Watching for file changes with StatReloader
INFO 2024-04-02 13:20:55,388 autoreload 5972 7904 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 13:20:56,544 autoreload 904 8608 Watching for file changes with StatReloader
ERROR 2024-04-02 13:21:00,798 log 904 504 Internal Server Error: /create_orders/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 59, in create_orders
    prod = Products.objects.filter(pk=j).set()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'set'
ERROR 2024-04-02 13:21:00,811 basehttp 904 504 "GET /create_orders/ HTTP/1.1" 500 65596
INFO 2024-04-02 13:23:07,664 autoreload 904 8608 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 13:23:09,201 autoreload 6016 12028 Watching for file changes with StatReloader
INFO 2024-04-02 13:26:13,860 autoreload 6016 12028 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 13:26:16,561 autoreload 852 1812 Watching for file changes with StatReloader
INFO 2024-04-02 13:29:50,198 autoreload 852 1812 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 13:29:51,701 autoreload 8804 7516 Watching for file changes with StatReloader
INFO 2024-04-02 13:30:02,661 autoreload 8804 7516 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 13:30:04,121 autoreload 11744 4848 Watching for file changes with StatReloader
ERROR 2024-04-02 13:30:09,664 log 11744 6092 Internal Server Error: /create_orders/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 65, in create_orders
    tp *= prod.price()
          ^^^^^^^^^^^^
TypeError: 'decimal.Decimal' object is not callable
ERROR 2024-04-02 13:30:09,670 basehttp 11744 6092 "GET /create_orders/ HTTP/1.1" 500 65952
INFO 2024-04-02 13:30:46,671 autoreload 11744 4848 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 13:30:47,844 autoreload 9676 1476 Watching for file changes with StatReloader
ERROR 2024-04-02 13:30:50,121 log 9676 3752 Internal Server Error: /create_orders/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 65, in create_orders
    tp += prod.price()
          ^^^^^^^^^^^^
TypeError: 'decimal.Decimal' object is not callable
ERROR 2024-04-02 13:30:50,158 basehttp 9676 3752 "GET /create_orders/ HTTP/1.1" 500 65952
INFO 2024-04-02 13:33:34,379 autoreload 9676 1476 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 13:33:36,037 autoreload 3604 11008 Watching for file changes with StatReloader
ERROR 2024-04-02 13:33:42,808 log 3604 9776 Internal Server Error: /create_orders/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 66, in create_orders
    order = Orders(customer=custr,
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 564, in __init__
    _setattr(self, prop, value)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 659, in __set__
    raise TypeError(
TypeError: Direct assignment to the forward side of a many-to-many set is prohibited. Use products.set() instead.
ERROR 2024-04-02 13:33:42,818 basehttp 3604 9776 "GET /create_orders/ HTTP/1.1" 500 76882
INFO 2024-04-02 13:34:34,116 autoreload 3604 11008 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 13:34:35,326 autoreload 8708 1052 Watching for file changes with StatReloader
INFO 2024-04-02 13:35:34,333 autoreload 8708 1052 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 13:35:36,132 autoreload 10584 12068 Watching for file changes with StatReloader
INFO 2024-04-02 13:35:39,414 autoreload 10584 12068 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 13:44:49,640 autoreload 4556 11220 Watching for file changes with StatReloader
INFO 2024-04-02 13:45:03,505 basehttp 4556 6328 "GET / HTTP/1.1" 200 1043
ERROR 2024-04-02 13:45:16,249 log 4556 2252 Internal Server Error: /create_orders/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 66, in create_orders
    order = Orders(customer=custr,
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 564, in __init__
    _setattr(self, prop, value)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 659, in __set__
    raise TypeError(
TypeError: Direct assignment to the forward side of a many-to-many set is prohibited. Use products.set() instead.
ERROR 2024-04-02 13:45:16,257 basehttp 4556 2252 "GET /create_orders/ HTTP/1.1" 500 77188
INFO 2024-04-02 13:51:17,142 autoreload 4556 11220 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 13:51:18,467 autoreload 5924 9496 Watching for file changes with StatReloader
ERROR 2024-04-02 13:51:29,199 log 5924 6176 Internal Server Error: /create_orders/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 57, in create_orders
    order = Order.objects.create(client=client, ordered_date=timezone.now())
            ^^^^^
NameError: name 'Order' is not defined
ERROR 2024-04-02 13:51:29,368 basehttp 5924 6176 "GET /create_orders/ HTTP/1.1" 500 65161
INFO 2024-04-02 13:52:31,636 autoreload 5924 9496 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 13:52:32,743 autoreload 1988 8852 Watching for file changes with StatReloader
ERROR 2024-04-02 13:52:41,508 log 1988 7584 Internal Server Error: /create_orders/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 64, in create_orders
    order.products.add(prod)
    ^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 650, in __get__
    return self.related_manager_cls(instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 1069, in __init__
    raise ValueError(
ValueError: "<Orders: Orders object (None)>" needs to have a value for field "id" before this many-to-many relationship can be used.
ERROR 2024-04-02 13:52:41,518 basehttp 1988 7584 "GET /create_orders/ HTTP/1.1" 500 75879
INFO 2024-04-02 13:55:00,318 autoreload 1988 8852 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 13:55:01,602 autoreload 10484 3000 Watching for file changes with StatReloader
ERROR 2024-04-02 13:55:04,249 log 10484 7940 Internal Server Error: /create_orders/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 63, in create_orders
    order.products.add(prod)
    ^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 650, in __get__
    return self.related_manager_cls(instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 1069, in __init__
    raise ValueError(
ValueError: "<Orders: Orders object (None)>" needs to have a value for field "id" before this many-to-many relationship can be used.
ERROR 2024-04-02 13:55:04,280 basehttp 10484 7940 "GET /create_orders/ HTTP/1.1" 500 75728
INFO 2024-04-02 13:58:00,773 autoreload 10484 3000 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 13:58:02,066 autoreload 6384 11868 Watching for file changes with StatReloader
ERROR 2024-04-02 13:58:05,030 log 6384 10452 Internal Server Error: /create_orders/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: homeworkapp_orders.total_price

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 58, in create_orders
    order = Orders.objects.create(customer=Clients.objects.filter(pk=i).first())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: homeworkapp_orders.total_price
ERROR 2024-04-02 13:58:05,081 basehttp 6384 10452 "GET /create_orders/ HTTP/1.1" 500 155102
INFO 2024-04-02 13:59:10,534 autoreload 6384 11868 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\models.py changed, reloading.
INFO 2024-04-02 13:59:11,688 autoreload 2248 3412 Watching for file changes with StatReloader
ERROR 2024-04-02 13:59:17,859 log 2248 8028 Internal Server Error: /create_orders/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: homeworkapp_orders.total_price

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 58, in create_orders
    order = Orders.objects.create(customer=Clients.objects.filter(pk=i).first())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: homeworkapp_orders.total_price
ERROR 2024-04-02 13:59:17,922 basehttp 2248 8028 "GET /create_orders/ HTTP/1.1" 500 155102
INFO 2024-04-02 13:59:46,410 autoreload 2248 3412 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\models.py changed, reloading.
INFO 2024-04-02 13:59:47,646 autoreload 5520 1464 Watching for file changes with StatReloader
INFO 2024-04-02 14:03:55,778 autoreload 5520 1464 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\models.py changed, reloading.
INFO 2024-04-02 14:03:57,293 autoreload 3164 5056 Watching for file changes with StatReloader
ERROR 2024-04-02 14:04:05,485 log 3164 900 Internal Server Error: /create_orders/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: homeworkapp_orders.total_price

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 58, in create_orders
    order = Orders.objects.create(customer=Clients.objects.filter(pk=i).first())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: homeworkapp_orders.total_price
ERROR 2024-04-02 14:04:05,563 basehttp 3164 900 "GET /create_orders/ HTTP/1.1" 500 155102
INFO 2024-04-02 14:05:04,938 autoreload 3164 5056 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\models.py changed, reloading.
INFO 2024-04-02 14:05:06,728 autoreload 6252 11344 Watching for file changes with StatReloader
INFO 2024-04-02 14:07:15,030 autoreload 6252 11344 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 14:07:16,602 autoreload 9008 7800 Watching for file changes with StatReloader
ERROR 2024-04-02 14:07:20,641 log 9008 9164 Internal Server Error: /create_orders/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 63, in create_orders
    order.total_price.add(tp)
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'add'
ERROR 2024-04-02 14:07:20,697 basehttp 9008 9164 "GET /create_orders/ HTTP/1.1" 500 65688
INFO 2024-04-02 14:08:17,771 autoreload 9008 7800 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 14:08:19,030 autoreload 4692 11116 Watching for file changes with StatReloader
ERROR 2024-04-02 14:08:22,415 log 4692 9648 Internal Server Error: /create_orders/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: homeworkapp_orders.customer_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 64, in create_orders
    order.save()
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: homeworkapp_orders.customer_id
ERROR 2024-04-02 14:08:22,476 basehttp 4692 9648 "GET /create_orders/ HTTP/1.1" 500 146596
INFO 2024-04-02 14:10:51,867 autoreload 4692 11116 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 14:10:53,086 autoreload 1352 10568 Watching for file changes with StatReloader
ERROR 2024-04-02 14:10:57,964 log 1352 9172 Internal Server Error: /create_orders/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: homeworkapp_orders.customer_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 64, in create_orders
    order.save()
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: homeworkapp_orders.customer_id
ERROR 2024-04-02 14:10:58,097 basehttp 1352 9172 "GET /create_orders/ HTTP/1.1" 500 146757
INFO 2024-04-02 14:11:44,691 autoreload 1352 10568 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 14:11:45,766 autoreload 1688 2680 Watching for file changes with StatReloader
ERROR 2024-04-02 14:11:49,465 log 1688 6196 Internal Server Error: /create_orders/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 63, in create_orders
    order = Orders(customer=cust, total_price=tp, products=prod)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 564, in __init__
    _setattr(self, prop, value)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 659, in __set__
    raise TypeError(
TypeError: Direct assignment to the forward side of a many-to-many set is prohibited. Use products.set() instead.
ERROR 2024-04-02 14:11:49,476 basehttp 1688 6196 "GET /create_orders/ HTTP/1.1" 500 76750
INFO 2024-04-02 14:14:18,942 autoreload 1688 2680 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 14:14:20,576 autoreload 4600 8880 Watching for file changes with StatReloader
INFO 2024-04-02 14:16:13,940 autoreload 4600 8880 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 14:16:15,442 autoreload 6444 10848 Watching for file changes with StatReloader
INFO 2024-04-02 14:17:25,249 autoreload 6444 10848 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 14:17:26,277 autoreload 6404 9404 Watching for file changes with StatReloader
INFO 2024-04-02 14:17:33,172 basehttp 6404 9352 "GET / HTTP/1.1" 200 1043
ERROR 2024-04-02 14:17:52,760 log 6404 6744 Internal Server Error: /create_orders/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 57, in create_orders
    order = Orders(customer=Clients.objects.filter(pk=1))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 284, in __set__
    raise ValueError(
ValueError: Cannot assign "<QuerySet [<Clients: Clients object (1)>]>": "Orders.customer" must be a "Clients" instance.
ERROR 2024-04-02 14:17:52,780 basehttp 6404 6744 "GET /create_orders/ HTTP/1.1" 500 75845
INFO 2024-04-02 19:38:37,240 autoreload 988 2596 Watching for file changes with StatReloader
INFO 2024-04-02 19:39:04,691 autoreload 988 2596 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\urls.py changed, reloading.
INFO 2024-04-02 19:39:06,214 autoreload 8804 10296 Watching for file changes with StatReloader
INFO 2024-04-02 19:39:10,899 basehttp 8804 6588 "GET / HTTP/1.1" 200 1043
WARNING 2024-04-02 19:39:11,992 log 8804 6588 Not Found: /favicon.ico
WARNING 2024-04-02 19:39:11,998 basehttp 8804 6588 "GET /favicon.ico HTTP/1.1" 404 2632
ERROR 2024-04-02 19:39:21,830 log 8804 11672 Internal Server Error: /create_users_fake/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 50, in create_users_fake
    order.products.add(prod)
    ^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 650, in __get__
    return self.related_manager_cls(instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 1069, in __init__
    raise ValueError(
ValueError: "<Orders: Orders object (None)>" needs to have a value for field "id" before this many-to-many relationship can be used.
ERROR 2024-04-02 19:39:21,849 basehttp 8804 11672 "GET /create_users_fake/ HTTP/1.1" 500 76174
INFO 2024-04-02 19:40:35,358 autoreload 8804 10296 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 19:40:36,948 autoreload 4724 6024 Watching for file changes with StatReloader
ERROR 2024-04-02 19:40:40,583 log 4724 11120 Internal Server Error: /create_users_fake/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 49, in create_users_fake
    order = Orders(customer=client.id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 284, in __set__
    raise ValueError(
ValueError: Cannot assign "20": "Orders.customer" must be a "Clients" instance.
ERROR 2024-04-02 19:40:40,673 basehttp 4724 11120 "GET /create_users_fake/ HTTP/1.1" 500 76426
INFO 2024-04-02 19:41:10,085 autoreload 4724 6024 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 19:41:11,288 autoreload 9752 10224 Watching for file changes with StatReloader
ERROR 2024-04-02 19:41:15,284 log 9752 10252 Internal Server Error: /create_users_fake/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: homeworkapp_orders.total_price

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 50, in create_users_fake
    order.save()
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: homeworkapp_orders.total_price
ERROR 2024-04-02 19:41:15,358 basehttp 9752 10252 "GET /create_users_fake/ HTTP/1.1" 500 147049
INFO 2024-04-02 19:43:42,387 autoreload 9752 10224 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 19:43:43,836 autoreload 1508 3556 Watching for file changes with StatReloader
ERROR 2024-04-02 19:43:47,348 log 1508 10044 Internal Server Error: /create_users_fake/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: homeworkapp_orders.total_price

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 52, in create_users_fake
    order.save()
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: homeworkapp_orders.total_price
ERROR 2024-04-02 19:43:47,383 basehttp 1508 10044 "GET /create_users_fake/ HTTP/1.1" 500 147149
INFO 2024-04-02 19:46:04,250 autoreload 1508 3556 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 19:46:05,732 autoreload 10324 11652 Watching for file changes with StatReloader
ERROR 2024-04-02 19:46:08,611 log 10324 648 Internal Server Error: /create_users_fake/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: homeworkapp_orders.total_price

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 52, in create_users_fake
    order.save()
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: homeworkapp_orders.total_price
ERROR 2024-04-02 19:46:08,754 basehttp 10324 648 "GET /create_users_fake/ HTTP/1.1" 500 147185
INFO 2024-04-02 19:47:38,696 autoreload 10324 11652 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-02 19:54:28,536 autoreload 7584 11596 Watching for file changes with StatReloader
INFO 2024-04-02 19:54:30,832 basehttp 7584 1660 "GET / HTTP/1.1" 200 1043
INFO 2024-04-02 19:54:57,581 basehttp 7584 12064 "GET /create_users_fake/ HTTP/1.1" 200 2
INFO 2024-04-06 15:05:20,817 autoreload 9476 10472 Watching for file changes with StatReloader
INFO 2024-04-06 15:06:19,209 autoreload 9476 10472 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\urls.py changed, reloading.
INFO 2024-04-06 15:06:20,317 autoreload 7276 392 Watching for file changes with StatReloader
INFO 2024-04-06 15:06:24,914 basehttp 7276 7312 "GET / HTTP/1.1" 200 217
WARNING 2024-04-06 15:06:25,963 log 7276 7312 Not Found: /favicon.ico
WARNING 2024-04-06 15:06:25,968 basehttp 7276 7312 "GET /favicon.ico HTTP/1.1" 404 2624
WARNING 2024-04-06 15:06:41,826 log 7276 11380 Not Found: /client_orders/5
WARNING 2024-04-06 15:06:41,856 basehttp 7276 11380 "GET /client_orders/5 HTTP/1.1" 404 2636
INFO 2024-04-06 15:07:11,011 autoreload 7276 392 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\urls.py changed, reloading.
INFO 2024-04-06 15:07:12,441 autoreload 5144 9132 Watching for file changes with StatReloader
WARNING 2024-04-06 15:07:16,137 log 5144 8212 Not Found: /client_orders/5
WARNING 2024-04-06 15:07:16,138 basehttp 5144 8212 "GET /client_orders/5 HTTP/1.1" 404 2653
WARNING 2024-04-06 15:08:18,403 log 5144 11016 Not Found: /client_orders/2
WARNING 2024-04-06 15:08:18,405 basehttp 5144 11016 "GET /client_orders/2 HTTP/1.1" 404 2653
INFO 2024-04-06 15:12:44,176 autoreload 2700 11768 Watching for file changes with StatReloader
INFO 2024-04-06 15:12:47,660 basehttp 2700 11928 "GET / HTTP/1.1" 200 217
WARNING 2024-04-06 15:13:02,535 log 2700 3856 Not Found: /client_orders/2
WARNING 2024-04-06 15:13:02,537 basehttp 2700 3856 "GET /client_orders/2 HTTP/1.1" 404 2653
WARNING 2024-04-06 15:13:10,565 log 2700 6940 Not Found: /client_orders/24
WARNING 2024-04-06 15:13:10,568 basehttp 2700 6940 "GET /client_orders/24 HTTP/1.1" 404 2656
WARNING 2024-04-06 15:13:18,975 log 2700 4484 Not Found: /client_orders/5
WARNING 2024-04-06 15:13:18,994 basehttp 2700 4484 "GET /client_orders/5 HTTP/1.1" 404 2653
INFO 2024-04-06 15:15:23,652 autoreload 1712 10208 Watching for file changes with StatReloader
INFO 2024-04-06 15:15:27,726 basehttp 1712 5172 "GET / HTTP/1.1" 200 217
WARNING 2024-04-06 15:15:37,826 log 1712 4736 Not Found: /client_orders/5
WARNING 2024-04-06 15:15:37,830 basehttp 1712 4736 "GET /client_orders/5 HTTP/1.1" 404 2653
INFO 2024-04-06 15:17:48,868 autoreload 1712 10208 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 15:17:50,744 autoreload 11512 2472 Watching for file changes with StatReloader
INFO 2024-04-06 15:18:10,674 autoreload 11512 2472 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\urls.py changed, reloading.
INFO 2024-04-06 15:18:11,777 autoreload 10672 9760 Watching for file changes with StatReloader
WARNING 2024-04-06 15:18:15,193 log 10672 6176 Not Found: /client_orders/5
WARNING 2024-04-06 15:18:15,194 basehttp 10672 6176 "GET /client_orders/5 HTTP/1.1" 404 2654
INFO 2024-04-06 15:21:57,241 autoreload 10672 9760 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 15:21:59,010 autoreload 7604 8984 Watching for file changes with StatReloader
WARNING 2024-04-06 15:21:59,491 log 7604 7836 Not Found: /client_orders/5
WARNING 2024-04-06 15:21:59,494 basehttp 7604 7836 "GET /client_orders/5 HTTP/1.1" 404 2654
INFO 2024-04-06 15:22:26,143 autoreload 7604 8984 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 15:22:27,373 autoreload 6824 10428 Watching for file changes with StatReloader
WARNING 2024-04-06 15:22:34,423 log 6824 7448 Not Found: /client_orders/5
WARNING 2024-04-06 15:22:34,437 basehttp 6824 7448 "GET /client_orders/5 HTTP/1.1" 404 2654
INFO 2024-04-06 15:24:30,102 autoreload 6824 10428 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 15:24:31,721 autoreload 11496 8512 Watching for file changes with StatReloader
INFO 2024-04-06 15:25:04,701 autoreload 11496 8512 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 15:25:06,095 autoreload 6196 1820 Watching for file changes with StatReloader
INFO 2024-04-06 15:26:58,190 autoreload 6196 1820 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\urls.py changed, reloading.
INFO 2024-04-06 15:26:59,549 autoreload 10244 10372 Watching for file changes with StatReloader
WARNING 2024-04-06 15:27:06,308 log 10244 10740 Not Found: /client_orders/5
WARNING 2024-04-06 15:27:06,314 basehttp 10244 10740 "GET /client_orders/5 HTTP/1.1" 404 2655
INFO 2024-04-06 15:27:22,346 basehttp 10244 8040 "GET /about/ HTTP/1.1" 200 217
WARNING 2024-04-06 15:27:33,876 log 10244 6092 Not Found: /client_orders/5/
WARNING 2024-04-06 15:27:33,879 basehttp 10244 6092 "GET /client_orders/5/ HTTP/1.1" 404 2658
INFO 2024-04-06 15:28:37,966 autoreload 10244 10372 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\urls.py changed, reloading.
INFO 2024-04-06 15:28:39,138 autoreload 6800 6020 Watching for file changes with StatReloader
INFO 2024-04-06 15:39:53,706 autoreload 6800 6020 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 15:39:55,662 autoreload 10396 7544 Watching for file changes with StatReloader
WARNING 2024-04-06 15:40:06,776 log 10396 2880 Not Found: /client_orders/5/
WARNING 2024-04-06 15:40:06,778 basehttp 10396 2880 "GET /client_orders/5/ HTTP/1.1" 404 2655
WARNING 2024-04-06 15:40:24,062 log 10396 10444 Not Found: /clientorders/5/
WARNING 2024-04-06 15:40:24,064 basehttp 10396 10444 "GET /clientorders/5/ HTTP/1.1" 404 2652
WARNING 2024-04-06 15:41:10,758 log 10396 11224 Not Found: /clientorders/
WARNING 2024-04-06 15:41:10,763 basehttp 10396 11224 "GET /clientorders/ HTTP/1.1" 404 2646
INFO 2024-04-06 15:41:37,006 autoreload 10396 7544 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\urls.py changed, reloading.
INFO 2024-04-06 15:41:38,724 autoreload 4696 6872 Watching for file changes with StatReloader
ERROR 2024-04-06 15:41:45,594 log 4696 3500 Internal Server Error: /clientorders/5/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 33, in clientorders
    orders = Orders.objects.filter(customer=client)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 158, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\lookups.py", line 360, in get_prep_lookup
    raise ValueError(
ValueError: The QuerySet value for an exact lookup must be limited to one result using slicing.
ERROR 2024-04-06 15:41:45,627 basehttp 4696 3500 "GET /clientorders/5/ HTTP/1.1" 500 123191
INFO 2024-04-06 15:42:28,149 autoreload 4696 6872 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 15:42:29,828 autoreload 7096 10156 Watching for file changes with StatReloader
ERROR 2024-04-06 15:42:36,553 log 7096 7564 Internal Server Error: /clientorders/5/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 40, in clientorders
    return render(request, 'homeworkapp/clientorders.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: homeworkapp/clientorders.html
ERROR 2024-04-06 15:42:36,564 basehttp 7096 7564 "GET /clientorders/5/ HTTP/1.1" 500 82259
INFO 2024-04-06 15:44:26,999 autoreload 4492 6920 Watching for file changes with StatReloader
INFO 2024-04-06 15:44:30,497 basehttp 4492 10980 "GET /clientorders/5/ HTTP/1.1" 200 154
INFO 2024-04-06 15:47:14,087 autoreload 5064 12040 Watching for file changes with StatReloader
INFO 2024-04-06 15:47:18,385 basehttp 5064 9808 "GET /clientorders/5/ HTTP/1.1" 200 168
INFO 2024-04-06 15:47:22,455 basehttp 5064 6320 "GET /clientorders/5/ HTTP/1.1" 200 168
INFO 2024-04-06 15:48:33,235 autoreload 5064 12040 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 15:48:34,839 autoreload 11748 3916 Watching for file changes with StatReloader
INFO 2024-04-06 15:48:39,350 basehttp 11748 5172 "GET /clientorders/5/ HTTP/1.1" 200 155
INFO 2024-04-06 19:03:02,335 autoreload 9164 3048 Watching for file changes with StatReloader
INFO 2024-04-06 19:03:05,568 basehttp 9164 10964 "GET / HTTP/1.1" 200 217
INFO 2024-04-06 19:03:22,292 basehttp 9164 11272 "GET /clientorders/5/ HTTP/1.1" 200 279
INFO 2024-04-06 19:07:15,485 autoreload 9164 3048 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 19:07:17,307 autoreload 8644 10636 Watching for file changes with StatReloader
INFO 2024-04-06 19:07:20,693 basehttp 8644 10964 "GET /clientorders/5/ HTTP/1.1" 200 279
INFO 2024-04-06 19:08:43,232 autoreload 8644 10636 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 19:08:44,500 autoreload 11680 2224 Watching for file changes with StatReloader
ERROR 2024-04-06 19:08:47,994 log 11680 8824 Internal Server Error: /clientorders/5/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 33, in clientorders
    orders = Orders.objects.all.filter(customer=client)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'filter'
ERROR 2024-04-06 19:08:48,015 basehttp 11680 8824 "GET /clientorders/5/ HTTP/1.1" 500 65826
INFO 2024-04-06 19:09:14,911 autoreload 11680 2224 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 19:09:16,207 autoreload 8860 5968 Watching for file changes with StatReloader
INFO 2024-04-06 19:09:18,316 basehttp 8860 12244 "GET /clientorders/5/ HTTP/1.1" 200 279
INFO 2024-04-06 19:09:27,320 basehttp 8860 11696 "GET /clientorders/2/ HTTP/1.1" 200 279
INFO 2024-04-06 19:11:45,031 autoreload 10856 11516 Watching for file changes with StatReloader
INFO 2024-04-06 19:11:47,303 basehttp 10856 12244 "GET /clientorders/2/ HTTP/1.1" 200 379
INFO 2024-04-06 19:13:38,319 autoreload 10856 11516 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 19:13:39,999 autoreload 9152 12144 Watching for file changes with StatReloader
WARNING 2024-04-06 19:13:50,317 log 9152 11368 Not Found: /create_products/
WARNING 2024-04-06 19:13:50,348 basehttp 9152 11368 "GET /create_products/ HTTP/1.1" 404 2655
INFO 2024-04-06 19:14:14,056 autoreload 9152 12144 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\urls.py changed, reloading.
INFO 2024-04-06 19:14:17,038 autoreload 8 832 Watching for file changes with StatReloader
ERROR 2024-04-06 19:14:23,431 log 8 5588 Internal Server Error: /create_products/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 60, in create_products
    product.save()
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: database is locked
ERROR 2024-04-06 19:14:23,482 basehttp 8 5588 "GET /create_products/ HTTP/1.1" 500 146878
INFO 2024-04-06 19:14:41,369 basehttp 8 11500 "GET /create_products/ HTTP/1.1" 200 2
INFO 2024-04-06 19:14:54,305 basehttp 8 5968 "GET /clientorders/2/ HTTP/1.1" 200 379
INFO 2024-04-06 19:18:00,497 autoreload 12148 10460 Watching for file changes with StatReloader
INFO 2024-04-06 19:18:04,336 basehttp 12148 5628 "GET /clientorders/2/ HTTP/1.1" 200 379
INFO 2024-04-06 19:19:30,782 autoreload 12148 10460 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\urls.py changed, reloading.
INFO 2024-04-06 19:19:32,524 autoreload 460 7600 Watching for file changes with StatReloader
INFO 2024-04-06 19:21:25,859 autoreload 460 7600 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 19:21:27,832 autoreload 5044 1240 Watching for file changes with StatReloader
INFO 2024-04-06 19:22:34,916 autoreload 5044 1240 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 19:22:36,123 autoreload 12016 2996 Watching for file changes with StatReloader
ERROR 2024-04-06 19:22:41,419 log 12016 9532 Internal Server Error: /clientorders/2/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 39, in clientorders
    return render(request, 'homeworkapp/clientorders.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\defaulttags.py", line 198, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 279, in get_select
    related_klass_infos = self.get_related_selections(select, select_mask)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1367, in get_related_selections
    raise FieldError(
django.core.exceptions.FieldError: Invalid field name(s) given in select_related: 'product', 'order'. Choices are: customer
ERROR 2024-04-06 19:22:41,575 basehttp 12016 9532 "GET /clientorders/2/ HTTP/1.1" 500 192467
INFO 2024-04-06 19:24:20,210 autoreload 12016 2996 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 19:24:21,431 autoreload 3688 10328 Watching for file changes with StatReloader
ERROR 2024-04-06 19:24:25,068 log 3688 3360 Internal Server Error: /clientorders/2/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 38, in clientorders
    return render(request, 'homeworkapp/clientorders.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\defaulttags.py", line 198, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 279, in get_select
    related_klass_infos = self.get_related_selections(select, select_mask)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1367, in get_related_selections
    raise FieldError(
django.core.exceptions.FieldError: Invalid field name(s) given in select_related: 'order'. Choices are: customer
ERROR 2024-04-06 19:24:25,205 basehttp 3688 3360 "GET /clientorders/2/ HTTP/1.1" 500 191796
ERROR 2024-04-06 19:24:47,991 log 3688 12140 Internal Server Error: /clientorders/2/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 38, in clientorders
    return render(request, 'homeworkapp/clientorders.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\defaulttags.py", line 198, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 279, in get_select
    related_klass_infos = self.get_related_selections(select, select_mask)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1367, in get_related_selections
    raise FieldError(
django.core.exceptions.FieldError: Invalid field name(s) given in select_related: 'order'. Choices are: customer
ERROR 2024-04-06 19:24:48,063 basehttp 3688 12140 "GET /clientorders/2/ HTTP/1.1" 500 191784
ERROR 2024-04-06 19:25:05,983 log 3688 9372 Internal Server Error: /clientorders/2/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 38, in clientorders
    return render(request, 'homeworkapp/clientorders.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\defaulttags.py", line 198, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 279, in get_select
    related_klass_infos = self.get_related_selections(select, select_mask)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1367, in get_related_selections
    raise FieldError(
django.core.exceptions.FieldError: Invalid field name(s) given in select_related: 'order'. Choices are: customer
ERROR 2024-04-06 19:25:06,121 basehttp 3688 9372 "GET /clientorders/2/ HTTP/1.1" 500 191796
ERROR 2024-04-06 19:25:45,151 log 3688 2592 Internal Server Error: /clientorders/2/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 38, in clientorders
    return render(request, 'homeworkapp/clientorders.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\defaulttags.py", line 198, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 279, in get_select
    related_klass_infos = self.get_related_selections(select, select_mask)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1367, in get_related_selections
    raise FieldError(
django.core.exceptions.FieldError: Invalid field name(s) given in select_related: 'order'. Choices are: customer
ERROR 2024-04-06 19:25:46,363 basehttp 3688 2592 "GET /clientorders/2/ HTTP/1.1" 500 191784
INFO 2024-04-06 19:25:46,563 autoreload 3688 10328 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 19:25:49,917 autoreload 10572 772 Watching for file changes with StatReloader
INFO 2024-04-06 19:30:27,326 autoreload 10572 772 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 19:30:28,536 autoreload 10996 1580 Watching for file changes with StatReloader
INFO 2024-04-06 19:30:55,130 autoreload 10996 1580 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 19:30:56,442 autoreload 7776 12248 Watching for file changes with StatReloader
ERROR 2024-04-06 19:31:01,548 log 7776 8628 Internal Server Error: /clientorders/2/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 33, in clientorders
    orders = Orders.objects.prefetch_related('products').select_related('order_prods').filter(client_id=cl_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'client_id' into field. Choices are: customer, customer_id, date_ordered, id, products, total_price
ERROR 2024-04-06 19:31:01,602 basehttp 7776 8628 "GET /clientorders/2/ HTTP/1.1" 500 106582
INFO 2024-04-06 19:32:08,704 autoreload 7776 12248 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 19:32:10,191 autoreload 11380 836 Watching for file changes with StatReloader
ERROR 2024-04-06 19:32:13,322 log 11380 10392 Internal Server Error: /clientorders/2/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 38, in clientorders
    return render(request, 'homeworkapp/clientorders.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\defaulttags.py", line 198, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 279, in get_select
    related_klass_infos = self.get_related_selections(select, select_mask)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1367, in get_related_selections
    raise FieldError(
django.core.exceptions.FieldError: Invalid field name(s) given in select_related: 'order_prods'. Choices are: customer
ERROR 2024-04-06 19:32:13,386 basehttp 11380 10392 "GET /clientorders/2/ HTTP/1.1" 500 192029
INFO 2024-04-06 19:33:13,387 basehttp 11380 3156 "GET /clientorders/2/ HTTP/1.1" 200 155
ERROR 2024-04-06 19:34:02,970 log 11380 10632 Internal Server Error: /clientorders/2/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 38, in clientorders
    return render(request, 'homeworkapp/clientorders.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\template\defaulttags.py", line 198, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 279, in get_select
    related_klass_infos = self.get_related_selections(select, select_mask)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1367, in get_related_selections
    raise FieldError(
django.core.exceptions.FieldError: Invalid field name(s) given in select_related: 'order_prods'. Choices are: customer
ERROR 2024-04-06 19:34:03,072 basehttp 11380 10632 "GET /clientorders/2/ HTTP/1.1" 500 192041
INFO 2024-04-06 19:37:54,297 autoreload 11380 836 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 19:37:56,024 autoreload 7320 5144 Watching for file changes with StatReloader
INFO 2024-04-06 19:38:15,846 autoreload 7320 5144 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 19:38:17,096 autoreload 10012 9104 Watching for file changes with StatReloader
INFO 2024-04-06 19:39:02,855 autoreload 10012 9104 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 19:39:07,527 autoreload 120 3284 Watching for file changes with StatReloader
INFO 2024-04-06 19:41:59,651 autoreload 120 3284 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 19:42:01,891 autoreload 1768 716 Watching for file changes with StatReloader
INFO 2024-04-06 19:42:06,958 basehttp 1768 11956 "GET /clientorders/2/ HTTP/1.1" 200 411
INFO 2024-04-06 19:42:36,065 autoreload 1768 716 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 19:42:37,303 autoreload 5364 12072 Watching for file changes with StatReloader
INFO 2024-04-06 19:42:39,996 basehttp 5364 5124 "GET /clientorders/2/ HTTP/1.1" 200 279
INFO 2024-04-06 19:42:44,083 basehttp 5364 9636 "GET /clientorders/2/ HTTP/1.1" 200 279
INFO 2024-04-06 19:43:12,873 autoreload 5364 12072 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 19:43:13,995 autoreload 5828 6208 Watching for file changes with StatReloader
INFO 2024-04-06 19:43:16,981 basehttp 5828 7500 "GET /clientorders/2/ HTTP/1.1" 200 279
INFO 2024-04-06 19:43:54,734 basehttp 5828 4788 "GET /clientorders/2/ HTTP/1.1" 200 284
INFO 2024-04-06 19:44:37,846 basehttp 5828 11144 "GET /clientorders/2/ HTTP/1.1" 200 372
INFO 2024-04-06 19:45:25,757 basehttp 5828 2988 "GET /clientorders/2/ HTTP/1.1" 200 367
INFO 2024-04-06 19:46:07,820 basehttp 5828 644 "GET /clientorders/2/ HTTP/1.1" 200 372
INFO 2024-04-06 19:49:35,082 autoreload 5828 6208 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 19:49:37,039 autoreload 8444 1824 Watching for file changes with StatReloader
INFO 2024-04-06 19:49:42,271 basehttp 8444 11760 "GET /clientorders/2/ HTTP/1.1" 200 372
INFO 2024-04-06 19:51:42,639 basehttp 8444 7888 "GET /clientorders/2/ HTTP/1.1" 200 484
INFO 2024-04-06 19:52:26,650 autoreload 8444 1824 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 19:52:28,102 autoreload 6136 1304 Watching for file changes with StatReloader
INFO 2024-04-06 19:52:29,655 basehttp 6136 3356 "GET /clientorders/2/ HTTP/1.1" 200 484
INFO 2024-04-06 19:53:08,667 autoreload 6136 1304 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 19:53:10,682 autoreload 1320 8164 Watching for file changes with StatReloader
ERROR 2024-04-06 19:53:11,698 log 1320 5356 Internal Server Error: /clientorders/2/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 37, in clientorders
    ord[order.id] = order.products.title
                    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ManyRelatedManager' object has no attribute 'title'
ERROR 2024-04-06 19:53:11,706 basehttp 1320 5356 "GET /clientorders/2/ HTTP/1.1" 500 66307
INFO 2024-04-06 19:58:31,718 autoreload 1320 8164 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 19:58:33,521 autoreload 9924 7564 Watching for file changes with StatReloader
INFO 2024-04-06 19:59:07,598 autoreload 9924 7564 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 19:59:08,594 autoreload 836 7144 Watching for file changes with StatReloader
ERROR 2024-04-06 19:59:11,940 log 836 6992 Internal Server Error: /clientorders/2/
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py", line 37, in clientorders
    ord[order.id] = order.products_id
                    ^^^^^^^^^^^^^^^^^
AttributeError: 'Orders' object has no attribute 'products_id'
ERROR 2024-04-06 19:59:11,964 basehttp 836 6992 "GET /clientorders/2/ HTTP/1.1" 500 66257
INFO 2024-04-06 20:02:04,008 autoreload 836 7144 C:\Users\Lenovo\PycharmProjects\homework_django\my_project\homeworkapp\views.py changed, reloading.
INFO 2024-04-06 20:02:05,404 autoreload 3624 3672 Watching for file changes with StatReloader
INFO 2024-04-06 20:02:07,786 basehttp 3624 8892 "GET /clientorders/2/ HTTP/1.1" 200 480
INFO 2024-04-06 20:02:17,730 basehttp 3624 7176 "GET /clientorders/5/ HTTP/1.1" 200 483
INFO 2024-04-06 20:02:25,515 basehttp 3624 6060 "GET /clientorders/1/ HTTP/1.1" 200 642
